In [1]:
import pandas as pd

# Woking with JSON

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.0394
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.6910
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.8920
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,4.0500
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.0192
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,2.5600
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.1820
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.2080
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.2720
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-04,1775260801,0.2720

# Working with SQL

In [5]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 2.4 MB/s eta 0:00:05
     -- ------------------------------------- 0.8/11.9 MB 2.4 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 1.8 MB/s eta 0:00:06
     ------ --------------------------------- 1.8/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 1.7 MB/s eta 0:00:06
     -------- ------------------------------- 2.6/11.9 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 2.9/11.9 MB 1.6 MB/s eta 0:00:06
     ---------- ----------------------------- 3.1/11.9 MB 1.6 MB/s eta 0:00:06
     ----------- ---------------------------- 3.4/11.9 MB 1.5 MB/s eta 0:00:06
     ------------ --------------------------- 3.7/11.9 MB 1.5 MB/s eta 0:00:06
     ------------- -------------------------- 3.9/11.9 MB 1.5 MB/s eta 0:00:06
     -------------- ------------------------- 4.2/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.5/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.7/11.9 MB 1.4 MB/s eta 0:00:06
     --------------- ------------------------ 4.7/11.9 MB 1.4 MB/s eta 0:00:06
     ----------------- ---------------------- 5.2/11.9 MB 1.4 MB/s eta 0:00:05
     ----------------- ---------------------- 5.2/11.9 MB 1.4 MB/s eta 0:00:05
     ------------------ --------------------- 5.5/11.9 MB 1.3 MB/s eta 0:00:05
     ------------------- -------------------- 5.8/11.9 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 6.0/11.9 MB 1.3 MB/s eta 0:00:05
     -------------------- ------------------- 6.0/11.9 MB 1.3 MB/s eta 0:00:05
     --------------------- ------------------ 6.3/11.9 MB 1.3 MB/s eta 0:00:05
     ---------------------- ----------------- 6.6/11.9 MB 1.3 MB/s eta 0:00:05
     ----------------------- ---------------- 6.8/11.9 MB 1.2 MB/s eta 0:00:05
     ----------------------- ---------------- 7.1/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------ --------------- 7.3/11.9 MB 1.2 MB/s eta 0:00:04
     ------------------------- -------------- 7.6/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     -------------------------- ------------- 7.9/11.9 MB 1.2 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.2 MB/s eta 0:00:04
     ---------------------------- ----------- 8.4/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.2 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.2 MB/s eta 0:00:03
     ------------------------------ --------- 8.9/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 9.2/11.9 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 9.4/11.9 MB 1.1 MB/s eta 0:00:03
     -------------------------------- ------- 9.7/11.9 MB 1.1 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.1 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.1 MB/s eta 0:00:02
     ----------------------------------- ---- 10.5/11.9 MB 1.1 MB/s eta 0:00:02
     ------------------------------------ --- 10.7/11.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.1 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.1 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.1 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.1 MB/s  0:00:11
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=248051 sha256=55d5c2540e328f8588fced5c7e54d56555fa9ef84eff3979d17611e01ac47c65
  Stored in directory: c:\users\kunal\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~orch (C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\kunal\AppData\Roaming\Python\Python312\site-packages)

In [6]:
import mysql.connector

In [13]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="world"
)

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [27]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [28]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]